title: Configuration
data:
  error_404_entry: 059d4d8d-fc60-49f8-8823-7da10549e84e
  copyright_since: 2020
  privacy_statement_type: entry
  privacy_statement_entry: e55aac94-9e98-407a-b8c0-6fb9c3dad7e9
  cookie_notice_type: none
